version: '6.3'
services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - xmoney:/var/lib/mysql

volumes:
  xmoney:
